export const MODEL = {
  SET_CANVANSREF: 'SET_CANVANSREF',
  SET_BUTTERFLY: 'SET_BUTTERFLY',
  SET_ATTRFORM: 'SET_ATTRFORM',
}

export const PRODUCTS = {
  SET_PRODUCTS:'setProducts',
  DECREMENT_PRODUCT_INVENTORY: 'decrementProductInventory'
}